// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CountTo: typeof import('./src/components/CountTo/src/CountTo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FlowerShadow: typeof import('./src/components/FlowerShadow/index.vue')['default']
    FooterPage: typeof import('./src/components/WrapperPage/src/footerPage.vue')['default']
    Heart: typeof import('./src/components/Heart/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconAddMore: typeof import('./src/components/icons/IconAddMore.vue')['default']
    IconChangeLanguage: typeof import('./src/components/icons/IconChangeLanguage.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconRemind: typeof import('./src/components/icons/IconRemind.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTheme: typeof import('./src/components/icons/IconTheme.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ListItem: typeof import('./src/components/cchList/src/ListItem.vue')['default']
    Pie: typeof import('./src/components/echartsComp/Pie.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./src/components/cchList/src/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TestComp: typeof import('./src/components/testComp/index.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    WrapperPage: typeof import('./src/components/WrapperPage/src/wrapperPage.vue')['default']
  }
}
