export default {
  path: "/cssDemo",
  name: "cssDemo",
  meta: {
    title: "一些样式",
    icon: "Menu",
    isLink: "",
    isHide: false,
    isFull: false,
    isAffix: false,
    isKeepAlive: true,
  },
  redirect: "/demo/ripple",
  children: [
    {
      path: "/demo/ripple",
      name: "ripple",
      component: "/demo/ripple/index",
      // component: () => import("@/views/car/index.vue"),
      meta: {
        title: "水波纹",
        icon: "Apple",
        isLink: "",
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: "/demo/loading",
      name: "loading",
      component: "/demo/loading/index",
      // component: () => import("@/views/car/index.vue"),
      meta: {
        title: "加载中",
        icon: "Apple",
        isLink: "",
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: "/demo/stitchMonster",
      name: "stitchMonster",
      component: "/demo/stitchMonster/index",
      meta: {
        title: "究极缝合怪",
        icon: "Bicycle",
        isLink: "",
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: "/demo/bgfusion",
      name: "bgfusion",
      component: "/demo/BgFusion/index",
      meta: {
        title: "水滴融合",
        icon: "Apple",
        isLink: "",
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
    {
      path: "/demo/cssdemo",
      name: "cssdemo",
      component: "/demo/cssdemo/index",
      meta: {
        title: "常见样式",
        icon: "Star",
        isLink: "",
        isHide: false,
        isFull: false,
        isAffix: false,
        isKeepAlive: true,
      },
    },
  ],
};
