#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "====== start run commitlint ========="
# npx --no-install commitlint --edit "$1"
pnpm exec commitlint --edit "$1"
# pnpm dlx commitlint --edit \$1
echo "====== end run commitlint ========="
